'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace wdw
    
    Partial Public Class DetRevBySubContByDay
        
        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        
        '''<summary>
        '''Topmenu1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Topmenu1 As Global.topmenu
        
        '''<summary>
        '''lblFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFromDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFromDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnLoad control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLoad As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''lblToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblToDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblSub control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSub As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lstSub control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstSub As Global.System.Web.UI.WebControls.ListBox
        
        '''<summary>
        '''CrystalReportViewer2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CrystalReportViewer2 As Global.CrystalDecisions.Web.CrystalReportViewer
    End Class
End Namespace
