'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace wdw

    Partial Public Class client1

        '''<summary>
        '''lblErrorMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lstClientType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstClientType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSpouseName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSpouseName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSpouseName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSpouseName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblContactName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContactName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtContactName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtContactName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPrimary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPrimary As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPrimaryExch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPrimaryExch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPrimaryNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPrimaryNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblAlternate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAlternate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAlternateArea control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAlternateArea As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAlternateExch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAlternateExch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAlternateNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAlternateNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblCallBackMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCallBackMethod As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lstCallBackMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstCallBackMethod As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lstAccountType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstAccountType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblDiscount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDiscount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkCOD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCOD As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkActive As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Label3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSrchLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSrchLastName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSrchContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSrchContact As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSrchPrimaryArea control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSrchPrimaryArea As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSrchPrimaryExch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSrchPrimaryExch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSrchPrimaryNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSrchPrimaryNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSrchAlternateArea control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSrchAlternateArea As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSrchAlternateExch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSrchAlternateExch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSrchAlternateNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSrchAlternateNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSrchClientID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSrchClientID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnNewClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNewClient As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''UWGClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UWGClient As Global.Infragistics.WebUI.UltraWebGrid.UltraWebGrid

        '''<summary>
        '''lblClientType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblClientType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotes As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtBillingAddressID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBillingAddressID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lstPrimaryPhoneType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstPrimaryPhoneType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lstAltPhoneType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstAltPhoneType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSelect As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lstDiscount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstDiscount As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtPrimaryArea control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPrimaryArea As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAddr1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddr1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtState As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtZipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtZipCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label10 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtOther1Area control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOther1Area As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtOther1Exch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOther1Exch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtOther1Number control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOther1Number As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lstOther1PhoneType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstOther1PhoneType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtOther2Area control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOther2Area As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtOther2Exch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOther2Exch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtOther2Number control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOther2Number As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lstOther2PhoneType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstOther2PhoneType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlMore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlMore As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''dsaf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dsaf As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fsdf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsdf As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dfds control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dfds As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtClientID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtClientID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCreateUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCreateUser As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCreateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCreateDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtModifiedUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtModifiedUser As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtModifiedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtModifiedDate As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
