'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace wdw
    
    Partial Public Class schedGrid
        
        '''<summary>
        '''lstArea control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstArea As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''btnPrevMo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPrevMo As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnPrevWeek control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPrevWeek As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnNextWeek control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNextWeek As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnNextMo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNextMo As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnToday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnToday As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''lblTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTime As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTime As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnNewJob control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNewJob As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnSchedJob control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSchedJob As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnUnSchdJob control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUnSchdJob As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''txtBeginDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBeginDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtHiddenNewJobId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHiddenNewJobId As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''UWGDates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UWGDates As Global.Infragistics.WebUI.UltraWebGrid.UltraWebGrid
        
        '''<summary>
        '''UWGSched control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UWGSched As Global.Infragistics.WebUI.UltraWebGrid.UltraWebGrid
    End Class
End Namespace
