'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace wdw
    
    Partial Public Class topmenu
        
        '''<summary>
        '''UltraWebMenu1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UltraWebMenu1 As Global.Infragistics.WebUI.UltraWebNavigator.UltraWebMenu
    End Class
End Namespace
