'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace wdw
    
    Partial Public Class ScheduleRpt
        
        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        
        '''<summary>
        '''Topmenu1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Topmenu1 As Global.wdw.topmenu
        
        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''WebDateChooserFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WebDateChooserFrom As Global.Infragistics.WebUI.WebSchedule.WebDateChooser
        
        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''WebDateChooserTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WebDateChooserTo As Global.Infragistics.WebUI.WebSchedule.WebDateChooser
        
        '''<summary>
        '''lblErrorMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorMsg As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''UWGScheduleRpt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UWGScheduleRpt As Global.Infragistics.WebUI.UltraWebGrid.UltraWebGrid
    End Class
End Namespace
